export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_SUCCESS = 'DATA_SUCCESS';
export const DATA_FAILED = 'DATA_FAILED';
export const UPDATE_ACTIVE_PAGE = 'UPDATE_ACTIVE_PAGE';
export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';
